// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_uRJyHScx1YZYJamS6XlbfGj-1cTXfQ',
    appId: '1:57809757127:web:a784ff181da4ce52f42fe2',
    messagingSenderId: '57809757127',
    projectId: 'peeshop-cb2ea',
    authDomain: 'peeshop-cb2ea.firebaseapp.com',
    storageBucket: 'peeshop-cb2ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiO-aQNrMHVp9rCT8rhNBgRzLzKHsSLcM',
    appId: '1:57809757127:android:ab1e65e6d6605537f42fe2',
    messagingSenderId: '57809757127',
    projectId: 'peeshop-cb2ea',
    storageBucket: 'peeshop-cb2ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEdpVyuFAgO6ek27tOkkHNH5rbc_-JG3k',
    appId: '1:57809757127:ios:36d9393895cdaaabf42fe2',
    messagingSenderId: '57809757127',
    projectId: 'peeshop-cb2ea',
    storageBucket: 'peeshop-cb2ea.appspot.com',
    iosBundleId: 'com.example.uasPmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEdpVyuFAgO6ek27tOkkHNH5rbc_-JG3k',
    appId: '1:57809757127:ios:36d9393895cdaaabf42fe2',
    messagingSenderId: '57809757127',
    projectId: 'peeshop-cb2ea',
    storageBucket: 'peeshop-cb2ea.appspot.com',
    iosBundleId: 'com.example.uasPmo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK_uRJyHScx1YZYJamS6XlbfGj-1cTXfQ',
    appId: '1:57809757127:web:61fa9d19e69a7dfdf42fe2',
    messagingSenderId: '57809757127',
    projectId: 'peeshop-cb2ea',
    authDomain: 'peeshop-cb2ea.firebaseapp.com',
    storageBucket: 'peeshop-cb2ea.appspot.com',
  );
}
